const USER = {
    LOAD: 'USER_LOAD',
    LOAD_SUCCESS: 'USER_LOAD_SUCCESS',
    LOAD_FAIL: 'USER_LOAD_FAIL'
}

const POST = {
    LOAD: 'POST_LOAD',
    LOAD_SUCCESS: 'POST_LOAD_SUCCESS',
    LOAD_FAIL: 'POST_LOAD_FAIL'
}

export { USER, POST };